#!/usr/bin/env python3
"""Sync patched dashboard.html from upstream headroom.

Workflow:
1) Fetch upstream dashboard template.
2) Apply this repo's local patches:
   a) Unified Gateway Lanes panel (Copilot + Bedrock stats).
   b) Session hero card — show session-level $ savings, not lifetime total.
3) Validate required selectors/fields still exist.
4) Write scripts/runtime/headroom/dashboard.html.

Use --check to fail if the local file does not match the generated output.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

UPSTREAM_DEFAULT = (
    "https://raw.githubusercontent.com/chopratejas/headroom/main/"
    "headroom/dashboard/templates/dashboard.html"
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DASHBOARD_PATH = REPO_ROOT / "scripts" / "runtime" / "headroom" / "dashboard.html"

AUTOGENERATED_COMMENT = (
    "<!-- AUTO-GENERATED by scripts/runtime/headroom/sync_dashboard.py"
    " — do not edit directly. Run sync_dashboard.py to regenerate. -->\n"
)

INSERT_MARKER = """
        <template x-if="viewMode === 'history'">
""".lstrip("\n")

UNIFIED_PANEL_BLOCK = """
        <!-- Unified Lanes Panel (Copilot + Bedrock) -->
        <template x-if="stats.lanes">
            <div class="bg-surface rounded-lg p-4 border border-border mb-6">
                <div class="text-sm font-medium mb-4 text-gray-300">Unified Gateway Lanes</div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <!-- Copilot Lane -->
                    <div class="rounded-lg border border-border p-3">
                        <div class="flex items-center gap-2 mb-2">
                            <span class="w-2 h-2 rounded-full bg-emerald-400"></span>
                            <span class="text-xs font-medium text-gray-300">Copilot Lane :4000</span>
                        </div>
                        <div class="space-y-1 text-xs text-gray-400 font-mono">
                            <div class="flex justify-between">
                                <span>Requests</span>
                                <span x-text="stats.lanes?.copilot?.api_requests ?? stats.summary?.api_requests ?? 0"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Input tokens</span>
                                <span x-text="formatNumber(stats.tokens?.input ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Output tokens</span>
                                <span x-text="formatNumber(stats.tokens?.output ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Tokens saved</span>
                                <span x-text="formatNumber(stats.lanes?.copilot?.tokens_saved ?? stats.tokens?.saved ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Cached</span>
                                <span x-text="stats.lanes?.copilot?.requests_cached ?? stats.requests?.cached ?? 0"></span>
                            </div>
                        </div>
                    </div>
                    <!-- Bedrock Native Lane -->
                    <div class="rounded-lg border border-border p-3">
                        <div class="flex items-center gap-2 mb-2">
                            <span class="w-2 h-2 rounded-full"
                                  :class="stats.lanes?.bedrock_native?.available ? 'bg-violet-400' : 'bg-gray-600'"></span>
                            <span class="text-xs font-medium text-gray-300">Bedrock Native :4002</span>
                            <span x-show="!stats.lanes?.bedrock_native?.available"
                                  class="text-xs text-gray-600 italic">unavailable</span>
                        </div>
                        <div class="space-y-1 text-xs text-gray-400 font-mono">
                            <div class="flex justify-between">
                                <span>Requests</span>
                                <span x-text="stats.lanes?.bedrock_native?.api_requests ?? 0"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Input tokens</span>
                                <span x-text="formatNumber(stats.lanes?.bedrock_native?.input_tokens ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Output tokens</span>
                                <span x-text="formatNumber(stats.lanes?.bedrock_native?.output_tokens ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Tokens saved</span>
                                <span x-text="formatNumber(stats.lanes?.bedrock_native?.tokens_saved ?? 0)"></span>
                            </div>
                            <div class="flex justify-between">
                                <span>Cached</span>
                                <span x-text="stats.lanes?.bedrock_native?.requests_cached ?? 0"></span>
                            </div>
                            <template x-if="stats.lanes?.bedrock_native?.compression_pct > 0">
                                <div class="flex justify-between text-violet-400">
                                    <span>Avg compression</span>
                                    <span x-text="(stats.lanes?.bedrock_native?.compression_pct ?? 0).toFixed(1) + '%'"></span>
                                </div>
                            </template>
                            <template x-if="(stats.lanes?.bedrock_native?.shim_stats?.cache_write_tokens ?? 0) > 0 || (stats.lanes?.bedrock_native?.shim_stats?.cache_read_tokens ?? 0) > 0">
                                <div class="mt-1 pt-1 border-t border-border/30 space-y-1">
                                    <div class="flex justify-between text-violet-300">
                                        <span>AWS cache writes</span>
                                        <span x-text="formatNumber(stats.lanes?.bedrock_native?.shim_stats?.cache_write_tokens ?? 0)"></span>
                                    </div>
                                    <div class="flex justify-between text-violet-300">
                                        <span>AWS cache reads</span>
                                        <span x-text="formatNumber(stats.lanes?.bedrock_native?.shim_stats?.cache_read_tokens ?? 0)"></span>
                                    </div>
                                </div>
                            </template>
                        </div>
                    </div>
                </div>
                <!-- Unified totals -->
                <template x-if="stats.unified">
                    <div class="mt-3 pt-3 border-t border-border grid grid-cols-3 gap-3 text-center">
                        <div>
                            <div class="text-lg font-light tabular-nums text-gray-100" x-text="stats.unified?.api_requests ?? 0"></div>
                            <div class="text-xs text-gray-500 mt-0.5">Total requests</div>
                        </div>
                        <div>
                            <div class="text-lg font-light tabular-nums text-emerald-400" x-text="formatNumber(stats.unified?.tokens_saved ?? 0)"></div>
                            <div class="text-xs text-gray-500 mt-0.5">Tokens saved</div>
                        </div>
                        <div>
                            <div class="text-lg font-light tabular-nums text-gray-100" x-text="stats.unified?.requests_cached ?? 0"></div>
                            <div class="text-xs text-gray-500 mt-0.5">Cached</div>
                        </div>
                    </div>
                </template>
            </div>
        </template>

""".lstrip("\n")

# Upstream session-view hero shows lifetime compression savings, not session savings.
# Patch it to show the current session's total (compression + cache, all lanes).
SESSION_HERO_OLD = """\
            <!-- Savings ($) - proxy compression only, priced at model list rate -->
            <div class="bg-surface rounded-lg p-4 border border-border">
                <div class="text-xs text-gray-500 uppercase tracking-wide mb-1">Proxy $ Saved</div>
                <div class="flex items-baseline gap-2">
                    <span class="text-3xl font-light tabular-nums text-emerald-400" x-text="'$' + formatCurrency(stats.persistent_savings?.lifetime?.compression_savings_usd || 0)"></span>
                </div>
                <div class="mt-2 text-xs text-gray-500">
                    <span x-show="(stats.persistent_savings?.lifetime?.compression_savings_usd || 0) > 0"
                          x-text="formatNumber(stats.tokens?.proxy_compression_saved || 0) + ' proxy tokens only; ' + cliFilteringLabel + ' excluded from $'"></span>
                    <span x-show="!((stats.persistent_savings?.lifetime?.compression_savings_usd || 0) > 0)"
                          x-text="formatNumber(stats.requests?.total || 0) + ' requests processed'"></span>
                </div>
            </div>"""

SESSION_HERO_NEW = """\
            <!-- Savings ($) - session total (compression + AWS cache), all lanes -->
            <div class="bg-surface rounded-lg p-4 border border-border">
                <div class="text-xs text-gray-500 uppercase tracking-wide mb-1">Session $ Saved</div>
                <div class="flex items-baseline gap-2">
                    <span class="text-3xl font-light tabular-nums text-emerald-400" x-text="'$' + formatCurrency(stats.cost?.savings_usd || 0)"></span>
                </div>
                <div class="mt-2 text-xs text-gray-500">
                    <span x-show="(stats.cost?.savings_usd || 0) > 0"
                          x-text="'$' + formatCurrency(stats.cost?.compression_savings_usd || 0) + ' compress · $' + formatCurrency(stats.cost?.cache_savings_usd || 0) + ' cache'"></span>
                    <span x-show="!((stats.cost?.savings_usd || 0) > 0)"
                          x-text="formatNumber(stats.requests?.total || 0) + ' requests processed'"></span>
                </div>
                <div class="mt-1 text-xs text-gray-600" x-show="(stats.persistent_savings?.lifetime?.compression_savings_usd || 0) > 0">
                    Lifetime: <span x-text="'$' + formatCurrency(stats.persistent_savings?.lifetime?.compression_savings_usd || 0)"></span>
                </div>
            </div>"""


def fetch_upstream(url: str) -> str:
    try:
        with urlopen(url, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="strict")
    except URLError as exc:
        raise SystemExit(f"Failed to fetch upstream dashboard: {exc}") from exc


def apply_patch(upstream: str) -> str:
    if "Unified Gateway Lanes" in upstream:
        # Upstream eventually may gain this panel; keep idempotent behavior.
        return upstream

    if INSERT_MARKER not in upstream:
        raise SystemExit("Patch marker not found in upstream dashboard; patch must be updated.")

    patched = upstream.replace(INSERT_MARKER, UNIFIED_PANEL_BLOCK + INSERT_MARKER, 1)

    if SESSION_HERO_OLD in patched:
        patched = patched.replace(SESSION_HERO_OLD, SESSION_HERO_NEW, 1)
    else:
        print(
            "Warning: session hero patch target not found; upstream may have changed",
            file=sys.stderr,
        )

    # x-if="... !== null" uses strict inequality — undefined passes the guard unexpectedly.
    # Use loose != null so both null and undefined are excluded.
    patched = patched.replace(" !== null", " != null")

    return patched


def validate_dashboard(html: str) -> None:
    required_snippets = [
        'x-data="dashboard()"',
        "fetch('/stats?cached=1')",
        "fetch('/stats-history')",
        "Unified Gateway Lanes",
        "stats.lanes?.bedrock_native",
        "bedrock_native?.output_tokens",
        "shim_stats?.cache_write_tokens",
        "stats.unified?.api_requests",
        "stats.cost?.savings_usd",
    ]

    missing = [snippet for snippet in required_snippets if snippet not in html]
    if missing:
        joined = ", ".join(missing)
        raise SystemExit(f"Patched dashboard validation failed; missing snippets: {joined}")


def run(*, url: str, check: bool) -> int:
    upstream = fetch_upstream(url)
    patched = apply_patch(upstream)
    validate_dashboard(patched)

    current = DASHBOARD_PATH.read_text(encoding="utf-8") if DASHBOARD_PATH.exists() else ""
    final = AUTOGENERATED_COMMENT + patched

    if check:
        if current != final:
            print("dashboard.html drift detected: local file is not generated from upstream+patch")
            return 2
        print("dashboard.html is in sync")
        return 0

    if current == final:
        print("dashboard.html already up to date")
        return 0

    DASHBOARD_PATH.write_text(final, encoding="utf-8")
    print(f"updated {DASHBOARD_PATH}")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default=UPSTREAM_DEFAULT, help="Upstream raw dashboard URL")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check-only mode; fail if local dashboard differs from generated output",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    return run(url=args.url, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
